GET http://localhost:3000/api/short-links

### req.query
GET http://localhost:3000/api/short-links/123?q=codeit

### req.body
POST http://localhost:3000/api/short-links/123
Content-Type: application/json

{
    "title": "codeit"
}

### req.cookies
GET http://localhost:3000/api/short-links/123
Cookie: session-id=codeit1234

###
GET http://localhost:3000/api/qrcodes
